config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get 'about' => 'pages#about'
  
  root 'pages#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Crumblr</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
      
      <%= csrf_meta_tags %>
    </head>
  <body>
    <div class = "container">
        
        <div class="page-header">
          <ul class="nav nav-pills pull-right">
            <li>
              <%= link_to "Home", root_url %>
          </li>
          
          <li>
           <%= link_to "Manage Posts", posts_url %>    
          </li>
          
          <li>
          <%= link_to "About", about_url %>
          </li>
      </ul>
          <h1><%= link_to 'Crumblr.', '/' %><small> // home baked goodness</small></h1>
        </div>  
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                  <%= yield %>
              </div>
          </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
    this is a fart <%= link_to "fart city", "http://www.google.com"%>
</p>

app/views/pages/welcome.html.erb
<% @posts.each do |post| %>
    <%= render "posts/post", post:post %>
    
    <br>
    <br>
    <br>
<% end %>